const SCREENS = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  BRANDLIST_SCREEN: 'BRANDLIST_SCREEN',
  PRODUCTLIST_SCREEN: 'PRODUCTLIST_SCREEN',
  ORDER_SCREEN: 'ORDER_SCREEN',
  ORDER_HISTORY_SCREEN: 'ORDER_HISTORY_SCREEN',
};
